spring.application.name=fleet-service
server.port=8082

# Database Configuration
spring.datasource.url=jdbc:h2:mem:flexidrive_fleet_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console (Access at http://localhost:8082/h2-console)
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest